# Generated by Django 2.2.1 on 2019-07-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='React',
            new_name='Reaction',
        ),
    ]
